---
- name: Configure PHP for CLI
  loop:
    - option: upload_max_filesize
      value: 6M
    - option: post_max_size
      value: 6M
  community.general.ini_file:
    dest: /etc/php/{{ suitecrm_php_version }}/cli/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present

- name: Update PHP settings for Apache2
  loop:
    - option: upload_max_filesize
      value: 6M
    - option: post_max_size
      value: 6M
  community.general.ini_file:
    dest: /etc/php/{{ suitecrm_php_version }}/apache2/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
