# defaults/main.yml
#  _   _                  ____             __ _       
# | | | |___  ___ _ __   / ___|___  _ __  / _(_) __ _ 
# | | | / __|/ _ \ '__| | |   / _ \| '_ \| |_| |/ _` |
# | |_| \__ \  __/ |    | |__| (_) | | | |  _| | (_| |
#  \___/|___/\___|_|     \____\___/|_| |_|_| |_|\__, |
#                                               |___/ 

# Username of new admin
newadmin_username: serveradmin
newadmin_base_directory: "/home/{{ newadmin_username }}"
newadmin_passwd_directory: "{{ newadmin_base_directory }}/.passwd"
newadmin_password_file: "{{newadmin_passwd_directory}}/pass.txt"

#  ____ ____  _   _    ____             __ _       
# / ___/ ___|| | | |  / ___|___  _ __  / _(_) __ _ 
# \___ \___ \| |_| | | |   / _ \| '_ \| |_| |/ _` |
#  ___) |__) |  _  | | |__| (_) | | | |  _| | (_| |
# |____/____/|_| |_|  \____\___/|_| |_|_| |_|\__, |
#                                            |___/ 

newadmin_ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+PpHslH0sr9pmkLMU3CRfZfNbHoDprS3sly8L4MFHxhP7D14ylrJ31omY1qwXPKD1CjJGrQSkStQKwu15M0Yt3hPKEEebVj1PlOuGJct9L2CGk0SyYl0Hv7X8+RrOUQogJh0tHUJQUkYXpvPndS1xekn4EM3qCVJ+n2CsyZM+74jFZ9Fcl9IcRX7BZsm1eBvGfKxxTDZlzO2qOChJyjzOsDP96zS7yVXtxA4GCR3WiJjI+w5nJvcUrf8mtj8AyRRH0p4/yI5AXJwP7c4D5v8aH0Hp4q/0b6j1uBcaGOL1elJ55BrWpR08B0/kUJ6Mvw1xF9NRwMuWbN9+hSKucTWW5vVSHaYmJ4z0ZBFKnxYnBQhzWZmTCXG4pB2QSCf3sMQgZlNf/Ew2E4xVRjAwhx4rhNT0KLsV7X5DfyoY7OjDp7uFyTZ3jbzv4iXSGCVsDsHnAs49t2XyVbd8YVmoxY+QuHccY/4N/IdQQJW/F5QD1e2BYLAEzjYoDe88PUPGNq5sWZXNQcbQCKjt+xqEKRX5EhzAMqXZ6+2eB/CUkjpUzr4GqK6rNFwJu4q0jQaA7oyg6zv+PZiWlLACmdBhRcQdEOnhv0n69Oz1SNblMk5oGfo3tqHmBdF8UG8Q3QmCmKOCvG6jLxGtYw== user@example.com"
# If you need to include multiple SSH-keys, add them to the list.
additional_ssh_keys:
#  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD...."
  - ""
  - ""
  - ""